name: Create Diagram
on:
  push:
    branches:
      - master

jobs:
  create-diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: githubocto/repo-visualizer@v1
